# ada boost for regressor is not added

<img src='../../../../images/gdc.png'>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../../../../Datasets/placement.csv")
df.head()

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [21]:
# step 1 - we calculate log - odds as we calculate mean in regression beacuse on solving our 1st step by taking loss function as log loss we get that

df['log_odds']=np.log(df['placed'].value_counts()[1]/df['placed'].value_counts()[0])
df['probab(log-odds)']=1/1+np.exp(-df['log_odds'])

In [22]:
# calculating residual for stage 1

df['res1'] = df['placed'] - df['probab(log-odds)']
df.head()

   cgpa  placement_exam_marks  placed  log_odds  probab(log-odds)     res1
0  7.19                  26.0       1 -0.044007           2.04499 -1.04499
1  7.46                  38.0       1 -0.044007           2.04499 -1.04499
2  7.54                  40.0       1 -0.044007           2.04499 -1.04499
3  6.42                   8.0       1 -0.044007           2.04499 -1.04499
4  7.23                  17.0       0 -0.044007           2.04499 -2.04499

In [23]:
# training first descision tree

from sklearn.tree import DecisionTreeRegressor

reg1 = DecisionTreeRegressor(max_leaf_nodes=3, random_state=1)

reg1.fit(df.iloc[:,0:2].values, df.iloc[:,-1].values)

DecisionTreeRegressor(max_leaf_nodes=3, random_state=1)

In [25]:
df['leaf_no']=reg1.apply(df.iloc[:,0:2].values)

In [26]:
df.head()

,cgpa,placement_exam_marks,placed,log_odds,probab(log-odds),res1,leaf_no
0,7.19,26.0,1,-0.044007,2.04499,-1.04499,3
1,7.46,38.0,1,-0.044007,2.04499,-1.04499,3
2,7.54,40.0,1,-0.044007,2.04499,-1.04499,3
3,6.42,8.0,1,-0.044007,2.04499,-1.04499,1
4,7.23,17.0,0,-0.044007,2.04499,-2.04499,3

In [31]:
def return_logs(leaf):
    temp_df=df[df['leaf_no']==leaf]
    sum_res=temp_df['res1'].sum()
    den=sum(temp_df['probab(log-odds)']*(1-temp_df['probab(log-odds)']))
    return round(sum_res/den,2)
    
df['probab2']=df['probab(log-odds)']+df['leaf_no'].apply(return_logs)

df.head()

,cgpa,placement_exam_marks,placed,log_odds,probab(log-odds),res1,leaf_no,probab2
0,7.19,26.0,1,-0.044007,2.04499,-1.04499,3,2.77499
1,7.46,38.0,1,-0.044007,2.04499,-1.04499,3,2.77499
2,7.54,40.0,1,-0.044007,2.04499,-1.04499,3,2.77499
3,6.42,8.0,1,-0.044007,2.04499,-1.04499,1,2.68499
4,7.23,17.0,0,-0.044007,2.04499,-2.04499,3,2.77499

In [ ]:
# similarly or models can be added